In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]

In [3]:
a

[1, 2, 3, 4, 5]

In [33]:
arr=np.array(a,dtype=np.int64)

In [34]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [35]:
type(arr)

numpy.ndarray

In [36]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [37]:
np.random.randint(5,size=(5,20))

array([[0, 3, 2, 2, 4, 3, 0, 0, 3, 3, 3, 3, 2, 0, 1, 1, 3, 4, 3, 1],
       [3, 3, 3, 4, 4, 0, 1, 0, 4, 1, 1, 3, 3, 2, 3, 2, 3, 2, 2, 4],
       [3, 4, 3, 0, 4, 3, 1, 3, 1, 1, 1, 3, 3, 2, 0, 0, 3, 0, 2, 2],
       [0, 0, 0, 3, 3, 3, 3, 1, 2, 3, 2, 4, 1, 2, 0, 2, 0, 4, 2, 1],
       [3, 4, 3, 3, 1, 2, 4, 4, 3, 3, 0, 4, 1, 1, 1, 1, 3, 1, 2, 1]])

In [38]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [39]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [40]:
arr.dtype

dtype('int64')

In [ ]:
b=